    # arb_bot/config/secrets.yaml
    # !!! 重要: 此文件包含敏感信息，已被 .gitignore 忽略 !!!

    okx:
      apikey: "a3aa35f2-856c-4436-b2b1-f31bb5266934"       # 你的 OKX API Key
      secretkey: "CEC86A613AB3847AC3370A82DBD91093"    # 你的 OKX Secret Key
      passphrase: "Aojsi92408HUs%" # 你的 OKX Passphrase
      # 如果模拟盘和实盘的API Key不同，可以在这里分开定义
      # simulated_apikey: "YOUR_SIMULATED_APIKEY"
      # simulated_secretkey: "YOUR_SIMULATED_SECRETKEY"
      # simulated_passphrase: "YOUR_SIMULATED_PASSPHRASE"
    
