    # arb_bot/config/settings.yaml

    exchange:
      name: "okx"
      simulated: true # true 代表模拟盘, false 代表实盘 (对应SDK中的 flag 参数)
      # OKX 模拟盘和实盘的 WebSocket 和 REST API URL
      # 模拟盘 (brokerId=9999)
      websocket_base_url_public: "wss://wspap.okx.com:8443/ws/v5/public?brokerId=9999"
      websocket_base_url_private: "wss://wspap.okx.com:8443/ws/v5/private?brokerId=9999"
      rest_api_base_url: "https://www.okx.com" # SDK内部会处理模拟盘路径
      # 实盘 (如果需要)
      # websocket_base_url_public_real: "wss://ws.okx.com:8443/ws/v5/public"
      # websocket_base_url_private_real: "wss://ws.okx.com:8443/ws/v5/private"

    arbitrage:
      # 核心套利币种 (例如: USDT, BTC, ETH)
      # 程序将尝试寻找 USDT -> BTC -> ETH -> USDT 及反向路径
      # 请确保这些币种在OKX上有对应的现货交易对
      core_currencies: ["USDT", "BTC", "ETH"] # 示例, 请根据实际情况修改

      # 构成的交易对 (程序会尝试从core_currencies推断, 或在此明确指定)
      # 格式: "BASE-QUOTE"
      # e.g., for USDT, BTC, ETH: ["BTC-USDT", "ETH-BTC", "ETH-USDT"]
      trading_pairs:
        - "BTC-USDT"
        - "ETH-BTC"
        - "ETH-USDT"
        # 如果你的核心币种是 USDT, USD, BTC (假设USD是某种稳定币如USDC)
        # 并且OKX上有 BTC-USDT, BTC-USDC, USDC-USDT (你需要核实这些交易对)
        # - "BTC-USDT"
        # - "BTC-USDC"
        # - "USDC-USDT"

      min_profit_threshold: 0.002  # 最小利润率 (例如 0.2%)
      fee_rate: 0.001              # 单边交易手续费率 (例如 0.1%)
      trade_amount_usdt: 10.0      # 每次套利循环，第一步投入的USDT等值数量

    risk_mgmt:
      max_single_trade_usd_value: 100 # 单笔交易最大USD价值 (初步限制)
      slippage_tolerance: 0.001       # 滑点容忍度 (例如 0.1%)
      emergency_stop_loss_threshold: -0.05 # 连续亏损达到总投入的5%则停止 (示例)
      max_consecutive_losses: 5       # 最大连续亏损次数，达到则暂停

    logging:
      level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
      file: "arb_bot.log" # 日志文件名 (会存放在 arb_bot/logs/ 目录下)
      max_bytes: 10485760 # 10MB
      backup_count: 5

    websocket_channels: # OKX频道示例
      public:
        # 订阅订单簿 (深度信息)
        - {channel: "books", instType: "SPOT"} # instId 会由程序根据 trading_pairs 动态填充
        # 订阅最新成交
        - {channel: "trades", instType: "SPOT"} # instId 会由程序根据 trading_pairs 动态填充
        # 订阅行情 (可选, tickers数据不如books详细)
        # - {channel: "tickers", instType: "SPOT"}
      private:
        # 账户余额变化
        - {channel: "account", ccy: ""} # ccy留空表示所有币种，或指定如 "USDT", "BTC"
        # 订单更新
        - {channel: "orders", instType: "SPOT"} # instType可以是 SPOT, MARGIN, SWAP, FUTURES, OPTION 或 ANY

    other:
      heartbeat_interval: 25 # WebSocket 心跳间隔 (秒)
      api_retry_delay: 5     # API请求失败重试间隔 (秒)
      max_api_retries: 3       # API请求最大重试次数
    
