# arb_bot/config/settings.yaml

# OKX API 端点 - 这是脚本期望的结构
api:
  rest_endpoint: "https://www.okx.com" # SDK内部会处理模拟盘路径，所以主域名即可
  # 根据您原有的 simulated: true，这里使用模拟盘的 WebSocket URL
  ws_public: "wss://wspap.okx.com:8443/ws/v5/public?brokerId=9999"
  ws_private: "wss://wspap.okx.com:8443/ws/v5/private?brokerId=9999"

exchange: # 保留您原有的 exchange 部分，以备其他模块使用
  name: "okx"
  simulated: true # true 代表模拟盘, false 代表实盘
  # 以下为您原有的URL，新的api部分已提取所需信息
  websocket_base_url_public: "wss://wspap.okx.com:8443/ws/v5/public?brokerId=9999"
  websocket_base_url_private: "wss://wspap.okx.com:8443/ws/v5/private?brokerId=9999"
  rest_api_base_url: "https://www.okx.com"
  # 实盘 (如果需要)
  # websocket_base_url_public_real: "wss://ws.okx.com:8443/ws/v5/public"
  # websocket_base_url_private_real: "wss://ws.okx.com:8443/ws/v5/private"

arbitrage:
  core_currencies: ["USDT", "BTC", "ETH"]
  trading_pairs:
    - "BTC-USDT"
    - "ETH-BTC"
    - "ETH-USDT"
  min_profit_threshold: 0.002
  fee_rate: 0.001
  trade_amount_usdt: 10.0

risk_mgmt:
  max_single_trade_usd_value: 100
  slippage_tolerance: 0.001
  emergency_stop_loss_threshold: -0.05
  max_consecutive_losses: 5

logging:
  level: "INFO"
  file: "arb_bot.log"
  max_bytes: 10485760
  backup_count: 5

websocket_channels:
  public:
    - {channel: "books", instType: "SPOT"}
    - {channel: "trades", instType: "SPOT"}
  private:
    - {channel: "account", ccy: ""}
    - {channel: "orders", instType: "SPOT"}

other:
  heartbeat_interval: 25
  api_retry_delay: 5
  max_api_retries: 3

